"use client";
import { useState } from "react";
import { ArrowUpRightIcon, ClipboardDocumentIcon, MapPinIcon, CheckCircleIcon } from "@heroicons/react/24/outline";
import { getAssumptions, getBrand, getCopy, getPricing, getPvout } from "@/content/solar";
import { estimate, installment, money, number, packagesForBill, suggestKwp } from "@/lib/solar-calc";
import { MonthlyChart, PaybackChart } from "./YieldChart";
export default function PackageCalculator({ bill, setBill }: { bill: string; setBill: (value:string)=>void }) {
  const a=getAssumptions(), provinces=getPvout(), brand=getBrand();
  const [unit,setUnit]=useState<"money"|"kwh">("money"), [provinceId,setProvince]=useState(a.defaultProvince), [selectedId,setSelected]=useState(""), [months,setMonths]=useState(a.installment.defaultMonths), [copyState,setCopyState]=useState("");
  const province=provinces.find(p=>p.id===provinceId)!;
  const amount=Number(bill), valid=Number.isFinite(amount)&&amount>0;
  const packages=valid ? packagesForBill(getPricing(),amount,"money",a) : [];
  const selected=packages.find(p=>p.id===selectedId) ?? packages[0];
  const result=selected ? estimate(selected,province,a) : null;
  const loan=selected && result ? installment(selected.price,months,result.monthlySaving,a.installment.interestPerMonth) : null;
  const summary=selected && result ? `${brand.name}\nGói mẫu: ${selected.name}\nTỉnh: ${province.name}\nHóa đơn: ${money(amount)}/tháng\nCông suất: ${number(selected.kwp)} kWp; lưu trữ: ${number(selected.storageKwh)} kWh\nGiá mô phỏng: ${money(selected.price)}\nSản lượng: ${number(result.dailyKwh)} kWh/ngày\nTiết kiệm: ${money(result.monthlySaving)}/tháng\nHoàn vốn đơn giản: ${result.paybackYears===null ? "Không xác định" : `${number(result.paybackYears)} năm`}\nDữ liệu mẫu, cần khảo sát để báo giá.` : "";
  async function copySummary() { try { await navigator.clipboard.writeText(summary); setCopyState("Đã sao chép thông tin gói."); } catch { setCopyState("Chưa sao chép được. Bạn có thể chọn và sao chép nội dung bên dưới."); } }
  return <div className="solar-calculator">
    <div className="solar-calculator-inputs solar-card">
      <div><label className="solar-label" htmlFor="bill-range">Chọn nhanh dải hóa đơn</label><select id="bill-range" className="solar-input" value="" onChange={e=>{if(e.target.value){setBill(e.target.value);setUnit("money");setCopyState("");}}}><option value="">Chọn một dải tiền điện</option>{getCopy().billRanges.map(r=><option key={r.value} value={r.value}>{r.label} / tháng</option>)}</select></div>
      <div><label className="solar-label" htmlFor="bill-unit">Đơn vị nhập</label><select id="bill-unit" className="solar-input" value={unit} onChange={e=>setUnit(e.target.value as "money"|"kwh")}><option value="money">Tiền điện (đồng/tháng)</option><option value="kwh">Điện tiêu thụ (kWh/tháng)</option></select></div>
      <div><label className="solar-label" htmlFor="full-bill">{unit==="money"?"Nhập tiền điện / tháng":"Nhập điện tiêu thụ / tháng"}</label><input id="full-bill" className="solar-input" type="number" min="1" step="any" inputMode="decimal" value={bill===""?"":unit==="money"?bill:Number(bill)/a.electricityPrice} onChange={e=>{setBill(e.target.value===""?"":String(Number(e.target.value)*(unit==="kwh"?a.electricityPrice:1)));setCopyState("");}} /></div>
      <div><label className="solar-label" htmlFor="province">Tỉnh / thành phố lắp đặt</label><select id="province" className="solar-input" value={provinceId} onChange={e=>{setProvince(e.target.value);setCopyState("");}}>{provinces.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></div>
    </div>
    <div className="solar-calc-summary" aria-live="polite">{valid ? <><MapPinIcon className="solar-icon" /><p>Tại <strong>{province.name}</strong>, quy mô gợi ý để bù mức tiêu thụ: <strong>{number(suggestKwp(amount,"money","hoa-luoi",province,a))} kWp hòa lưới</strong> hoặc <strong>{number(suggestKwp(amount,"money","hybrid",province,a))} kWp hybrid</strong>.</p></> : <p role="status">Nhập số tiền hoặc điện tiêu thụ lớn hơn 0 để xem gói gợi ý.</p>}</div>
    <p className="solar-note">Gói được lọc theo dải hóa đơn mẫu; không tự động thiết kế hệ thống. Tiết kiệm theo tiềm năng tự dùng giả định, chưa giới hạn theo hóa đơn hay phụ tải thực tế.</p>
    <div className="solar-package-grid">{packages.map(pkg=>{const r=estimate(pkg,province,a);return <article className={`solar-package solar-card ${selected?.id===pkg.id?"is-selected":""}`} key={pkg.id} data-package={pkg.id}>
      <div className="solar-package-top"><span className="solar-status">{pkg.type==="hybrid"?"Có lưu trữ":"Tự dùng ban ngày"}</span><button type="button" className="solar-select-package" aria-pressed={selected?.id===pkg.id} onClick={()=>{setSelected(pkg.id);setCopyState("");}}><CheckCircleIcon />{selected?.id===pkg.id?"Đang chọn":"Chọn gói"}</button></div>
      <h3>{pkg.name}</h3><div className="solar-package-power">{number(pkg.kwp)} <span>kWp</span>{pkg.storageKwh>0&&<small> + {number(pkg.storageKwh)} kWh lưu trữ</small>}</div><p className="solar-package-price">{money(pkg.price)} <span>Giá mẫu</span></p>
      <dl className="solar-metrics"><div><dt>Sản lượng / ngày</dt><dd>{number(r.dailyKwh)} kWh</dd></div><div><dt>Tiết kiệm / tháng</dt><dd>{money(r.monthlySaving)}</dd></div><div><dt>Hoàn vốn đơn giản</dt><dd>{r.paybackYears===null?"Không xác định":`${number(r.paybackYears)} năm`}</dd></div></dl>
      <details className="solar-package-details"><summary>Thiết bị và biểu đồ riêng của gói</summary><ul>{pkg.equipment.map(e=><li key={e}>{e}</li>)}</ul><p>{pkg.phases} pha · cần khoảng {number(pkg.roofM2,0)} m² mái</p><p>{pkg.warranty}</p><MonthlyChart result={r} name={pkg.name} /><PaybackChart result={r} name={pkg.name} /></details>
    </article>;})}</div>
    {selected&&result&&loan&&<div className="solar-after-calculation"><div className="solar-card solar-installment"><div className="solar-kicker">Cân đối dòng tiền</div><h3>Trả góp cần bù thêm bao nhiêu mỗi tháng?</h3><p>Tiền góp trừ phần tiết kiệm là số tiền còn cần thu xếp.</p><label className="solar-label" htmlFor="months">Kỳ hạn: <strong>{months} tháng</strong></label><input id="months" type="range" min={a.installment.minMonths} max={a.installment.maxMonths} step="1" value={months} onChange={e=>setMonths(Number(e.target.value))} /><div className="solar-range-ends"><span>{a.installment.minMonths} tháng</span><span>{a.installment.maxMonths} tháng</span></div><dl className="solar-metrics"><div><dt>Tiền góp / tháng</dt><dd>{money(loan.payment)}</dd></div><div><dt>Tiết kiệm / tháng</dt><dd>{money(loan.monthlySaving)}</dd></div><div><dt>{loan.extra>=0?"Thực bù thêm":"Tiết kiệm còn lại"}</dt><dd>{money(Math.abs(loan.extra))}</dd></div></dl><p className="solar-note">Gói đang chọn: {selected.name}. Mô phỏng góp đều với lãi mẫu {number(a.installment.interestPerMonth*100)}%/tháng, chưa gồm phí/trả trước. Không phải đề nghị tín dụng.</p></div>
      <div className="solar-card solar-yield"><div className="solar-kicker">Tra sản lượng địa phương</div><h3>Nắng ở {province.name} tạo được bao nhiêu điện?</h3><dl className="solar-metrics"><div><dt>PVout giả định</dt><dd>{number(province.pvout)} kWh/kWp/ngày</dd></div><div><dt>Sau PR, mỗi 1 kWp</dt><dd>{number(province.pvout*a.pr)} kWh/ngày</dd></div><div><dt>Gói đang chọn</dt><dd>{number(result.dailyKwh)} kWh/ngày</dd></div></dl><p className="solar-note">Số mẫu chưa xác minh, không phải số đo tại mái. Nguồn để đối chiếu: <a href={province.source} target="_blank" rel="noreferrer">Global Solar Atlas</a>; cần khảo sát bóng che và hướng mái.</p><details className="solar-accordion"><summary>Bảng đầy đủ {provinces.length} tỉnh / thành phố</summary><div className="solar-table-scroll" tabIndex={0} role="region" aria-label="Bảng số liệu có thể cuộn"><table><caption>PVout mô phỏng, chưa xác minh</caption><thead><tr><th scope="col">Tỉnh / thành phố</th><th scope="col">kWh/kWp/ngày</th></tr></thead><tbody>{provinces.map(p=><tr key={p.id}><th scope="row">{p.name}</th><td>{number(p.pvout)}</td></tr>)}</tbody></table></div></details></div>
      <div className="solar-quote"><div><strong>Tiếp tục từ phương án bạn vừa chọn.</strong><p>Chia sẻ thông tin gói để đội kỹ thuật trao đổi về mái và phụ tải của bạn.</p></div><div className="solar-quote-actions"><button type="button" className="solar-button" onClick={copySummary}><ClipboardDocumentIcon />Sao chép thông tin gói</button><a className="solar-button solar-button-accent" href={selected.contactSegment==="home"?brand.zalo.home:brand.zalo.business} target="_blank" rel="noreferrer">Nhận báo giá qua Zalo <ArrowUpRightIcon /></a></div><p className="solar-note" role="status">{copyState}</p><details><summary>Xem thông tin có thể sao chép</summary><textarea className="solar-input" aria-label="Thông tin gói đã chọn" readOnly rows={10} value={summary} /></details></div>
    </div>}
    <details className="solar-accordion solar-assumptions"><summary>Công thức và giả định đang dùng</summary><p>Sản lượng/ngày = kWp × PVout × PR ({number(a.pr)}). Tiết kiệm/tháng = sản lượng/ngày × 30 × giá điện ({money(a.electricityPrice)}/kWh) × tỷ lệ tự dùng (hòa lưới {number(a.selfUse["hoa-luoi"]*100)}%, hybrid {number(a.selfUse.hybrid*100)}%). Hoàn vốn = giá gói ÷ tiết kiệm/năm. Ròng tích lũy = tiết kiệm/năm × số năm − giá gói.</p><p>{a.source} {getCopy().faq.find(f=>f.question.includes("bảo trì"))?.answer}</p></details>
  </div>;
}
