"use client";
import { useId, useState } from "react";
import { getAssumptions, getSegments } from "@/content/solar";
import SectionHeading from "./SectionHeading";
export default function SegmentComparison() {
  const segments=getSegments(), [index,setIndex]=useState(0), id=useId(), selected=segments[index], a=getAssumptions();
  const points=(values:number[])=>values.map((v,h)=>`${45+h/23*535},${190-v/100*140}`).join(" ");
  return <section className="solar-section" id="giai-phap"><div className="solar-container"><SectionHeading step="03" label="Theo cách dùng điện" title="Hòa lưới hay hybrid phù hợp với bạn?" answer="Hòa lưới tận dụng điện ban ngày, hybrid bổ sung lưu trữ. Lựa chọn cần đối chiếu giờ dùng điện, nhu cầu dự phòng và vốn đầu tư." />
    <div className="solar-segment-tabs" role="tablist" aria-label="Phân khúc sử dụng điện">{segments.map((s,i)=><button type="button" role="tab" id={`${id}-tab-${i}`} key={s.id} aria-selected={i===index} aria-controls={`${id}-panel`} tabIndex={i===index?0:-1} onClick={()=>setIndex(i)} onKeyDown={e=>{let next=i;if(e.key==="ArrowRight")next=(i+1)%segments.length;else if(e.key==="ArrowLeft")next=(i+segments.length-1)%segments.length;else if(e.key==="Home")next=0;else if(e.key==="End")next=segments.length-1;else return;e.preventDefault();setIndex(next);document.getElementById(`${id}-tab-${next}`)?.focus();}}>{s.label}</button>)}</div>
    <div role="tabpanel" id={`${id}-panel`} aria-labelledby={`${id}-tab-${index}`} className="solar-comparison-grid">
      <div className="solar-card"><h3>{selected.title}</h3><p>{selected.answer}</p><figure className="solar-chart solar-day-chart"><figcaption>Nhịp nắng và tiêu thụ điện trong ngày</figcaption><div className="solar-chart-legend"><span><i className="solar-legend-sun" />Nắng</span><span><i className="solar-legend-load" />Tiêu thụ</span></div><svg viewBox="0 0 620 235" role="img" aria-labelledby={`${id}-chart`}><title id={`${id}-chart`}>Biểu đồ 24 giờ mô phỏng cho {selected.label}; chỉ số tương đối, không phải kWh đo thực</title>{[0,50,100].map(v=><g key={v}><line x1="45" y1={190-v/100*140} x2="580" y2={190-v/100*140} className="solar-chart-axis" /><text x="30" y={194-v/100*140} textAnchor="end">{v}</text></g>)}<polyline points={points(a.solarProfile)} className="solar-chart-solar-line" fill="none" strokeWidth="4" /><polyline points={points(selected.consumption)} className="solar-chart-consumption" fill="none" strokeWidth="3" strokeDasharray="7 3" />{[0,6,12,18,23].map(h=><text key={h} x={45+h/23*535} y="218" textAnchor="middle">{h}h</text>)}</svg><p className="solar-note">Mẫu phụ tải minh họa, đơn vị tương đối 0–100. Nắng dùng đường liền; tiêu thụ dùng đường đứt để phân biệt khi không thấy màu.</p><details><summary>Xem số liệu 24 giờ</summary><div className="solar-table-scroll"><table><caption>Chỉ số tương đối theo giờ</caption><thead><tr><th scope="col">Giờ</th><th scope="col">Nắng</th><th scope="col">Tiêu thụ</th></tr></thead><tbody>{selected.consumption.map((v,h)=><tr key={h}><th scope="row">{h}h</th><td>{a.solarProfile[h]}</td><td>{v}</td></tr>)}</tbody></table></div></details></figure></div>
      <div><div className="solar-table-scroll"><table className="solar-compare-table"><caption>Đối chiếu cho {selected.label}</caption><thead><tr><th scope="col">Tiêu chí</th><th scope="col">Hòa lưới</th><th scope="col">Hybrid</th></tr></thead><tbody><tr><th scope="row">Lợi thế</th><td>{selected.advantages["hoa-luoi"]}</td><td>{selected.advantages.hybrid}</td></tr><tr><th scope="row">Cần cân nhắc</th><td>{selected.limitations["hoa-luoi"]}</td><td>{selected.limitations.hybrid}</td></tr></tbody></table></div><div className="solar-recommendation"><strong>Điểm cần khảo sát</strong><p>{selected.recommendation}</p></div></div>
    </div>
  </div></section>;
}
