"use client";
import { useState } from "react";
import { getAssumptions, getBrand, getCopy, getLegal, getProjects, getSegments } from "@/content/solar";
import { CheckCircleIcon } from "@heroicons/react/24/outline";
import BillHero from "./BillHero";
import SectionHeading from "./SectionHeading";
import LeadForm from "@/components/LeadForm";
export default function SolarHome() {
  const [bill, setBill] = useState(String(getAssumptions().defaultBill));
  const copy = getCopy(), brand = getBrand();
  return <main id="noi-dung" className="solar-home">
    <BillHero bill={bill} setBill={setBill} />
    <section className="solar-section"><div className="solar-container"><SectionHeading step="01" label="Hiểu bài toán" title="Tiền điện đang lấy đi cơ hội nào?" answer="Chi phí điện đều đặn làm thu hẹp ngân sách cho những việc khác. Đầu tư hiệu quả bắt đầu từ việc hiểu phụ tải của chính bạn." /><div className="solar-problem-grid">{copy.problems.map((p,i) => <article key={p.title}><span className="solar-index">0{i+1}</span><h3>{p.title}</h3><p>{p.text}</p></article>)}</div></div></section>
    <section id="tinh-toan" className="solar-section solar-surface"><div className="solar-container"><SectionHeading step="02" label="Tính trước khi chọn" title="Hóa đơn của bạn phù hợp công suất nào?" answer="Công suất phù hợp phụ thuộc nơi lắp đặt và thời điểm dùng điện. Hóa đơn giúp xác định quy mô để bắt đầu cuộc trao đổi kỹ thuật." /><div className="solar-card"><p>Gói hòa lưới giúp tự dùng điện ban ngày; hybrid bổ sung lưu trữ cho thời gian khác. Mỗi cấu hình cần đối chiếu giá, thiết bị và điều kiện mái.</p></div></div></section>
    <section className="solar-section"><div className="solar-container"><SectionHeading step="03" label="Chọn theo cách dùng điện" title="Cùng một mái nhà, vì sao cần giải pháp khác nhau?" answer="Lịch sử dụng điện quyết định lợi ích của hệ thống. So sánh theo phân khúc giúp bạn chọn đúng câu hỏi trước khi chọn thiết bị." /><div className="solar-three-grid">{getSegments().map(s => <article className="solar-card" key={s.id}><CheckCircleIcon className="solar-icon" /><h3>{s.label}</h3><p>{s.answer}</p></article>)}</div></div></section>
    <section className="solar-section solar-surface"><div className="solar-container"><SectionHeading step="04" label="Đối chiếu bằng chứng" title="Một dự án phù hợp cần cho bạn thấy gì?" answer="Cần thấy công suất, sản lượng, tiết kiệm và cấu hình trong cùng một bối cảnh vận hành. Những tình huống dưới đây là mô phỏng để minh họa cách đối chiếu." /><div className="solar-three-grid">{getProjects().slice(0,3).map(p => <article className="solar-card" key={p.id}><h3>{p.title}</h3><p>{p.description}</p></article>)}</div></div></section>
    <section className="solar-section"><div className="solar-container"><SectionHeading step="05" label="Minh bạch từ đầu" title="Pháp lý nào cần xác nhận trước khi lắp?" answer="Danh mục hồ sơ phụ thuộc công trình và phương án đấu nối. Các mục chưa chắc chắn phải được xác minh trước khi sử dụng cho dự án thực." />{getLegal().map(l => <details className="solar-accordion" key={l.id}><summary>{l.question}</summary><p>{l.answer}</p><a href={l.source} target="_blank" rel="noreferrer">Tra cứu nguồn chính thức</a></details>)}</div></section>
    <section className="solar-section solar-surface"><div className="solar-container solar-faq-grid"><SectionHeading step="06" label="Gỡ vướng mắc" title="Bạn còn băn khoăn điều gì?" answer="Bạn có thể xem cách tính và giới hạn của mô phỏng trước khi liên hệ." /><div>{copy.faq.map(f => <details className="solar-accordion" key={f.question}><summary>{f.question}</summary><p>{f.answer}</p></details>)}</div></div></section>
    <section id="lien-he" className="solar-section"><div className="solar-container solar-contact-grid"><div><SectionHeading step="07" label="Bước tiếp theo" title="Muốn biết mái của bạn có phù hợp?" answer="Hãy chuẩn bị hóa đơn và ảnh mái. Một cuộc trao đổi kỹ thuật sẽ giúp làm rõ phương án khảo sát." /><p>{brand.address}</p><a className="solar-contact-phone" href={`tel:${brand.hotlines[0].phone}`}>{brand.hotlines[0].phone}</a><p className="solar-note">{copy.demoNotice}</p></div><div className="solar-card solar-contact-form"><LeadForm source="website" /></div></div></section>
  </main>;
}
