import Link from "next/link";
import { ArrowRightIcon, BoltIcon, ChartBarSquareIcon, CheckCircleIcon, CpuChipIcon, ShieldCheckIcon } from "@heroicons/react/24/outline";
import { SITE_CONFIG } from "@/config/site";
import { PROJECTS } from "@/data/solar";
import RoiCalculator from "@/components/RoiCalculator";
import LeadForm from "@/components/LeadForm";
import EnergyMonitoringSection from "@/components/EnergyMonitoringSection";

const load=[34,31,30,29,31,40,58,76,89,96,100,98,92,95,101,103,99,91,82,69,56,48,42,37];
const solar=[0,0,0,0,0,4,18,42,67,84,96,100,94,82,66,44,21,6,0,0,0,0,0,0];
const pts=(values:number[])=>values.map((v,i)=>`${24+(i/(values.length-1))*552},${194-(v/110)*176}`).join(" ");
const checks=[
  ["01","Phân tích phụ tải","Phân tích phụ tải theo giờ, ca sản xuất, tải nền và công suất đỉnh."],
  ["02","Mái & kết cấu","Rà soát mái, vùng đặt pin, tải trọng và phương án chống dột."],
  ["03","Thiết kế điện","Tính toán chuỗi pin, tải Inverter, bảo vệ AC/DC và phương án đấu nối."],
  ["04","Mô phỏng sản lượng","Mô phỏng sản lượng, clipping, tổn hao và tỷ lệ tự dùng theo năm."],
  ["05","Hồ sơ an toàn","Phân vùng thi công, LOTO, danh mục kiểm tra QA/QC và nghiệm thu."],
  ["06","Sẵn sàng vận hành & bảo trì (O&M)","Thiết kế để khoanh vùng lỗi và bảo trì ít ảnh hưởng vận hành."],
];
const finance=[
  ["Quy mô đề xuất","1.000 kWp","Theo phụ tải ban ngày"],
  ["Sản lượng năm 1","~1,43 GWh","Mô phỏng sơ bộ"],
  ["Tỷ lệ tự dùng","92%","Giảm điện dư phát lên lưới"],
  ["Tiết kiệm năm 1","~1,44 tỷ","Theo giả định biểu giá"],
  ["Thời gian hoàn vốn đơn giản","~5,8 năm","Kịch bản cơ sở"],
  ["IRR dự kiến","~18,6%","Dữ liệu mẫu"],
];

function Kpi({label,value,note}:{label:string;value:string;note?:string}){return <div className="t8-glass-dark rounded-2xl p-4"><div className="text-[10px] font-black uppercase tracking-[.18em] text-white/60">{label}</div><div className="mt-2 text-2xl font-black">{value}</div>{note&&<div className="mt-1 text-xs text-white/65">{note}</div>}</div>}

function PowerChart({light=false}:{light?:boolean}){return <svg viewBox="0 0 600 220" className="mt-4 w-full" role="img" aria-label="Biểu đồ phụ tải và sản lượng điện mặt trời 24 giờ">
  {[50,95,140,185].map(y=><line key={y} x1="24" y1={y} x2="576" y2={y} stroke={light?"#d8dee7":"rgba(255,255,255,.08)"}/>)}
  <polyline points={pts(load)} fill="none" stroke={light?"#071b33":"rgba(255,255,255,.75)"} strokeWidth="3" vectorEffect="non-scaling-stroke"/>
  <polyline points={pts(solar)} fill="none" stroke="#f5b927" strokeWidth="4" vectorEffect="non-scaling-stroke"/>
  <text x="24" y="214" fill={light?"#64748b":"rgba(255,255,255,.4)"} fontSize="10">00:00</text><text x="281" y="214" fill={light?"#64748b":"rgba(255,255,255,.4)"} fontSize="10">12:00</text><text x="544" y="214" fill={light?"#64748b":"rgba(255,255,255,.4)"} fontSize="10">24:00</text>
</svg>}

export default function IndustrialSolarHomepage(){return <main className="overflow-hidden">
  <section className="relative overflow-hidden bg-[var(--t5-primary)] text-white">
    <div className="absolute inset-0 opacity-20 [background-image:linear-gradient(rgba(255,255,255,.09)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,.09)_1px,transparent_1px)] [background-size:48px_48px]"/>
    <div className="absolute inset-y-0 right-0 hidden w-[38%] bg-[var(--t5-burgundy)]/20 [clip-path:polygon(28%_0,100%_0,100%_100%,0_100%)] lg:block"/>
    <div className="t5-container relative grid min-h-[760px] items-center gap-10 py-16 lg:grid-cols-[.92fr_1.08fr]">
      <div data-reveal="left"><div className="inline-flex rounded-full backdrop-blur items-center gap-2 border border-[var(--t5-accent)]/45 bg-[var(--t5-accent)]/10 px-3 py-2 text-[11px] font-black uppercase tracking-[.2em] text-[var(--t5-accent)]"><span className="h-2 w-2 rounded-full bg-[var(--t5-accent)]"/>Kỹ thuật điện mặt trời công nghiệp</div>
      <h1 className="mt-7 text-4xl font-black leading-[1.08] tracking-[-.045em] sm:text-5xl lg:text-6xl">Biến điện năng trở thành <span className="text-[var(--t5-accent)]">lợi nhuận</span> cho doanh nghiệp của bạn</h1>
      <p className="mt-7 max-w-2xl text-lg leading-8 text-white/70">Từ biểu đồ phụ tải, sơ đồ một sợi, mô phỏng sản lượng đến hồ sơ tài chính — mọi quyết định đầu tư đều được giải thích bằng dữ liệu kỹ thuật.</p>
      <div className="mt-9 flex flex-wrap gap-3"><a href="#engineering" className="t5-button bg-[var(--t5-accent)] text-[var(--t5-primary)]">Xem hồ sơ kỹ thuật <ArrowRightIcon className="h-4 w-4"/></a><Link href="/contact-us" className="t5-button border border-white/25 text-white">Yêu cầu hồ sơ đề xuất</Link></div>
      <div className="mt-12 grid grid-cols-2 gap-3 sm:grid-cols-4">{[[`${SITE_CONFIG.capabilities.mwp} MWp`,"danh mục dự án"],[`${SITE_CONFIG.capabilities.projects}+`,"dự án"],["24/7","giám sát"],["IEC","tiêu chuẩn thiết kế"]].map(([v,l])=><div key={l} className="t8-glass-dark rounded-2xl p-4"><div className="text-xl font-black text-[var(--t5-accent)]">{v}</div><div className="mt-1 text-[10px] font-black uppercase tracking-[.15em] text-white/60">{l}</div></div>)}</div></div>
      <div data-reveal="right" className="t8-glass-dark t8-float-slow rounded-[28px] p-4 shadow-2xl sm:p-6"><div className="flex items-center justify-between border-b border-white/10 pb-4"><div><div className="text-[10px] font-black uppercase tracking-[.2em] text-white/60">Trung tâm giám sát năng lượng</div><div className="mt-1 font-black">Nhà máy A / Tổng quan thời gian thực</div></div><div className="flex items-center gap-2 text-xs font-bold text-emerald-300"><span className="h-2 w-2 rounded-full bg-emerald-400"/>Trực tuyến</div></div>
      <div className="mt-4 grid gap-3 sm:grid-cols-4"><Kpi label="Công suất PV" value="782 kW" note="78% công suất đỉnh"/><Kpi label="Phụ tải" value="846 kW" note="Đang sản xuất"/><Kpi label="Điện lưới" value="64 kW" note="Mua từ lưới"/><Kpi label="Hôm nay" value="4.82 MWh" note="+6.4%"/></div>
      <div className="mt-3 rounded-2xl border border-white/15 bg-white/5 p-4"><div className="text-xs font-black uppercase tracking-[.14em] text-white/65">Biểu đồ công suất 24 giờ</div><PowerChart/></div>
      <div className="mt-3 rounded-2xl border-l-4 border-[var(--t5-burgundy)] bg-[var(--t5-burgundy)]/20 p-4 text-sm font-bold leading-6">Tính công suất theo vùng phụ tải 08:00–16:00 để tối ưu tỷ lệ tự dùng, không chỉ tối đa số tấm pin.</div></div>
    </div>
  </section>

  <section id="engineering" className="t5-section"><div className="t5-container"><div className="grid gap-8 lg:grid-cols-[.72fr_1.28fr]"><div><span className="t5-eyebrow">Phân tích phụ tải</span><h2 data-reveal="down" className="t5-heading">Thiết kế bắt đầu từ đường cong phụ tải, không phải diện tích mái.</h2></div><p data-reveal="up" className="t5-subheading lg:ml-auto">Mô hình 24 giờ cho thấy tải nền, công suất đỉnh và vùng thời gian điện mặt trời tạo giá trị cao nhất.</p></div>
  <div className="mt-10 grid gap-6 lg:grid-cols-[1.35fr_.65fr]"><div data-reveal="left" className="t8-card bg-slate-50/80 p-6"><div className="text-xs font-black uppercase tracking-[.16em] text-slate-400">Ngày làm việc điển hình / dữ liệu tổng hợp mỗi 15 phút</div><h3 className="mt-1 text-xl font-black text-[var(--t5-primary)]">Biểu đồ phụ tải nhà máy — 24 giờ</h3><PowerChart light/></div><div data-reveal-stagger="right" className="grid gap-3">{[["Công suất đỉnh","1.03 MW"],["Phụ tải nền ban ngày","0.76 MW"],["Mức phù hợp điện mặt trời","92%"],["Rủi ro điện dư","Thấp"]].map(([l,v])=><div key={l} className="t8-card p-6"><div className="text-xs font-black uppercase tracking-[.15em] text-slate-400">{l}</div><div className="mt-3 text-3xl font-black text-[var(--t5-primary)]">{v}</div></div>)}</div></div></div></section>

  <section className="t5-section bg-[#f4f5f7]"><div className="t5-container"><span className="t5-eyebrow">Sơ đồ một sợi</span><h2 data-reveal="down" className="t5-heading">Một sơ đồ đủ rõ để kỹ thuật, vận hành và chủ đầu tư cùng nói chung một ngôn ngữ.</h2>
  <div className="mt-10 t8-card overflow-x-auto p-6"><svg viewBox="0 0 1100 340" className="min-w-[860px] w-full" role="img" aria-label="Sơ đồ một sợi hệ thống điện mặt trời nhà xưởng"><defs><marker id="a" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8 z" fill="#8c1d2c"/></marker></defs>
  {[[20,"DÀN PIN PV","1,000 kWp"],[300,"DC / INVERTER","8 × 125 kW"],[580,"TỦ GOM AC","Thanh cái 400 V"],[860,"TỦ ĐIỆN HẠ ÁP CHÍNH","Phụ tải nhà máy"]].map(([x,t,v],i)=><g key={String(t)}><rect x={Number(x)} y="100" width="210" height="130" rx="18" fill={i%2===0?"#071b33":"#fff"} stroke="#cbd5e1"/><text x={Number(x)+24} y="140" fill={i%2===0?"#f5b927":"#8c1d2c"} fontSize="12" fontWeight="800">{t}</text><text x={Number(x)+24} y="180" fill={i%2===0?"#fff":"#071b33"} fontSize="24" fontWeight="800">{v}</text>{i<3&&<line x1={Number(x)+210} y1="165" x2={Number(x)+275} y2="165" stroke="#8c1d2c" strokeWidth="4" markerEnd="url(#a)"/>}</g>)}
  <line x1="965" y1="100" x2="965" y2="45" stroke="#071b33" strokeWidth="3"/><rect x="890" y="12" width="150" height="36" fill="#f5b927"/><text x="920" y="35" fill="#071b33" fontSize="12" fontWeight="900">LƯỚI ĐIỆN</text><line x1="685" y1="230" x2="685" y2="290" stroke="#071b33" strokeWidth="3"/><rect x="590" y="288" width="190" height="40" fill="#8c1d2c"/><text x="625" y="313" fill="white" fontSize="12" fontWeight="900">EMS / SCADA</text></svg></div>
  <div className="mt-6 grid gap-3 md:grid-cols-3">{[["Phối hợp bảo vệ","Aptomat, SPD, bộ cách ly và điểm cô lập rõ ràng."],["Kiến trúc đo đếm","Đủ dữ liệu để đối soát sản lượng và hiệu suất từng vùng."],["Khả năng bảo trì","Bảo trì từng khu vực với ảnh hưởng vận hành tối thiểu."]].map(([t,d],i)=><div key={t} className={`rounded-2xl border-l-4 bg-white/80 p-5 shadow-sm text-sm leading-6 text-slate-600 ${i===0?"border-[var(--t5-burgundy)]":i===1?"border-[var(--t5-accent)]":"border-[var(--t5-primary)]"}`}><strong className="block text-[var(--t5-primary)]">{t}</strong>{d}</div>)}</div></div></section>

  <section className="t5-section bg-[var(--t5-primary)] text-white"><div className="t5-container"><span className="t5-eyebrow !text-[var(--t5-accent)]">Mô phỏng giám sát vận hành</span><h2 data-reveal="down" className="mt-4 max-w-4xl text-4xl font-black tracking-[-.045em] sm:text-5xl">Sau nghiệm thu, hệ thống vẫn phải “nói chuyện” được với đội vận hành.</h2>
  <div className="mt-10 grid gap-4 lg:grid-cols-[1.2fr_.8fr]"><div className="t8-glass-dark rounded-[28px] p-5"><div className="flex justify-between border-b border-white/10 pb-4"><div><div className="text-[10px] font-black uppercase tracking-[.18em] text-white/60">Hiệu suất hệ thống</div><div className="mt-1 text-xl font-black">Tháng 10 / tháng hiện tại</div></div><div className="text-right"><div className="text-[10px] text-white/60">TỶ SỐ HIỆU SUẤT (PR)</div><div className="text-3xl font-black text-[var(--t5-accent)]">82.7%</div></div></div><div className="mt-5 grid gap-3 sm:grid-cols-3"><Kpi label="Sản lượng" value="112.4 MWh" note="+3,8% so với kế hoạch"/><Kpi label="Tự dùng" value="103.8 MWh" note="92.3%"/><Kpi label="Khả dụng" value="99.72%" note="30 ngày gần nhất"/></div><div className="mt-7 grid grid-cols-12 items-end gap-2 border-b border-white/10 pb-2">{[42,58,68,52,78,87,91,73,88,95,84,96].map((v,i)=><div key={i} className="bg-[var(--t5-accent)]/80" style={{height:`${Math.round(v*1.25)}px`}}/>)}</div></div>
  <div className="space-y-4"><div className="t8-glass-dark rounded-[28px] p-5"><div className="flex justify-between"><strong>Cảnh báo đang hoạt động</strong><span className="rounded-full bg-[var(--t5-burgundy)] px-2 py-1 text-[10px] font-black">2 CẢNH BÁO</span></div>{[["INV-05","Dòng DC không cân bằng"],["ZONE-C","Sản lượng -8,2% so với mức chuẩn"]].map(([a,b])=><div key={a} className="mt-3 rounded-2xl border border-white/15 bg-white/5 p-4"><strong>{a}</strong><div className="mt-1 text-sm text-white/55">{b}</div></div>)}</div><div className="grid grid-cols-2 gap-4"><div className="t8-glass-dark rounded-[28px] p-5"><CpuChipIcon className="h-6 w-6 text-[var(--t5-accent)]"/><div className="mt-4 text-2xl font-black">8 / 8</div><div className="text-xs text-white/60">Inverter đang trực tuyến</div></div><div className="t8-glass-dark rounded-[28px] p-5"><ShieldCheckIcon className="h-6 w-6 text-[var(--t5-accent)]"/><div className="mt-4 text-2xl font-black">14 phút</div><div className="text-xs text-white/60">xử lý cảnh báo</div></div></div></div></div></div></section>

  <EnergyMonitoringSection />

  <section className="t5-section"><div className="t5-container grid gap-8 lg:grid-cols-[.68fr_1.32fr]"><div><span className="t5-eyebrow">Kiểm soát kỹ thuật</span><h2 data-reveal="down" className="t5-heading">Hồ sơ triển khai có điểm kiểm soát rõ ràng, không dựa vào kinh nghiệm truyền miệng.</h2></div><div data-reveal-stagger="up" className="grid gap-4 sm:grid-cols-2">{checks.map(([n,t,d])=><article key={n} className="t8-card p-6"><div className="flex justify-between"><span className="font-black text-[var(--t5-burgundy)]">{n}</span><CheckCircleIcon className="h-5 w-5 text-[var(--t5-accent)]"/></div><h3 className="mt-7 text-xl font-black text-[var(--t5-primary)]">{t}</h3><p className="mt-3 text-sm leading-7 text-slate-600">{d}</p></article>)}</div></div></section>

  <RoiCalculator/>

  <section className="t5-section bg-[#f4f5f7]"><div className="t5-container grid gap-10 lg:grid-cols-[.78fr_1.22fr]"><div><span className="t5-eyebrow">Hồ sơ tài chính</span><h2 data-reveal="down" className="t5-heading">Một hồ sơ để Giám đốc tài chính (CFO) đọc được, kỹ sư kiểm tra được và ban giám đốc quyết định được.</h2><p data-reveal="up" className="t5-subheading">Phương án đầu tư trình bày giả định, sản lượng, tiết kiệm, thời gian hoàn vốn và điều kiện cần xác minh trước đầu tư.</p></div><div data-reveal="right" className="t8-card overflow-hidden shadow-xl"><div className="flex justify-between bg-[var(--t5-primary)] p-5 text-white"><div><div className="text-[10px] font-black uppercase tracking-[.18em] text-white/65">Tóm tắt phương án đầu tư</div><div className="mt-1 text-xl font-black">Điện mặt trời mái nhà — Nhà máy A</div></div><div className="bg-[var(--t5-accent)] px-3 py-2 text-xs font-black text-[var(--t5-primary)]">KỊCH BẢN CƠ SỞ</div></div>{finance.map(([l,v,n])=><div key={l} className="grid grid-cols-[1fr_auto] gap-6 border-b border-slate-200 p-5"><div><div className="font-bold text-slate-700">{l}</div><div className="mt-1 text-xs text-slate-400">{n}</div></div><div className="text-xl font-black text-[var(--t5-primary)]">{v}</div></div>)}<div className="grid gap-px bg-slate-200 sm:grid-cols-3">{[["CAPEX","~12.8 tỷ"],["Dự phòng rủi ro","3–5%"],["Điều kiện quyết định","Khảo sát"]].map(([l,v],i)=><div key={l} className={i===1?"bg-[#f9ecee] p-5":"bg-white p-5"}><div className="text-[10px] font-black uppercase tracking-[.16em] text-[var(--t5-burgundy)]">{l}</div><div className="mt-2 text-2xl font-black text-[var(--t5-primary)]">{v}</div></div>)}</div><p className="p-4 text-[11px] leading-5 text-slate-400">Số liệu mẫu cho trang web mẫu, không phải cam kết đầu tư. Hồ sơ thực tế cần dữ liệu tải, khảo sát mái và báo giá tại thời điểm triển khai.</p></div></div></section>

  <section className="t5-section"><div className="t5-container"><span className="t5-eyebrow">Dự án tiêu biểu</span><h2 data-reveal="down" className="t5-heading">Từ thiết kế đến dữ liệu vận hành sau bàn giao.</h2><div className="mt-10 grid gap-4 lg:grid-cols-3">{PROJECTS.map((p,i)=><Link key={p.slug} href={`/project/${p.slug}`} data-reveal="up" className="t8-card group p-6 transition hover:-translate-y-1 hover:border-[var(--t5-burgundy)] hover:shadow-xl"><div className="flex justify-between"><span className="text-xs font-black text-slate-400">REF-{String(i+1).padStart(2,"0")}</span><ChartBarSquareIcon className="h-5 w-5 text-[var(--t5-burgundy)]"/></div><h3 className="mt-10 text-xl font-black text-[var(--t5-primary)]">{p.title}</h3><div className="mt-2 text-sm text-slate-500">{p.type} • {p.location}</div><div className="mt-6 grid grid-cols-2 border-t border-slate-200 pt-5"><strong>{p.capacity}</strong><strong>{p.selfUse} tự dùng</strong></div></Link>)}</div></div></section>

  <section className="border-t-[10px] border-[var(--t5-burgundy)] bg-[var(--t5-primary)] py-16 text-white"><div className="t5-container grid gap-10 lg:grid-cols-[.78fr_1.22fr]"><div><div className="flex h-12 w-12 rounded-2xl items-center justify-center bg-[var(--t5-accent)] text-[var(--t5-primary)]"><BoltIcon className="h-7 w-7"/></div><h2 data-reveal="down" className="mt-6 text-4xl font-black tracking-[-.045em]">Nhận phương án kỹ thuật + hồ sơ tài chính cho nhà máy của bạn.</h2><p className="mt-5 max-w-xl leading-8 text-white/60">Gửi hóa đơn điện, giờ vận hành và thông tin mái để buổi khảo sát tập trung vào ROI và khả năng triển khai.</p></div><div data-reveal="right" className="t8-card p-6 text-slate-900 md:p-8"><LeadForm source="template-9-engineering-proposal"/></div></div></section>
</main>}
