"use client";
import Image from "next/image";
import Link from "next/link";
import { Service } from "@/types";

export default function ServiceCard({ service }: { service: Service }) {
  const labels: Record<string,string>={household:"Hộ gia đình",business:"Doanh nghiệp",maintenance:"Bảo trì",consultation:"Tư vấn"};
  return <Link href={`/service/${service.id}`} className="group block h-full"><article className="flex h-full flex-col overflow-hidden border border-emerald-950/10 bg-white transition duration-300 hover:-translate-y-1 hover:border-emerald-700/30 hover:shadow-[0_18px_45px_color-mix(in srgb,var(--solar-primary-dark) 10%,transparent)]"><div className="relative aspect-[16/10] overflow-hidden"><Image src={service.image} alt={service.title} fill className="object-cover transition duration-500 group-hover:scale-105" sizes="(max-width:768px) 100vw, 33vw" /><span className="absolute left-4 top-4 rounded-md bg-[var(--solar-primary)] px-3 py-1.5 text-xs font-black text-[var(--solar-primary-dark)]">{labels[service.category]||"Dịch vụ"}</span></div><div className="flex flex-1 flex-col p-6"><h3 className="text-xl font-black tracking-tight text-[var(--solar-primary-dark)] group-hover:text-[var(--solar-primary-dark)]">{service.title}</h3><p className="mt-3 line-clamp-3 leading-7 text-slate-600">{service.description}</p><ul className="mt-5 space-y-2">{service.features.slice(0,3).map((feature)=><li key={feature} className="flex gap-2 text-sm text-slate-600"><span className="mt-1 text-[var(--solar-primary-dark)]">●</span>{feature}</li>)}</ul><div className="mt-auto flex items-end justify-between border-t border-emerald-950/10 pt-5"><div><div className="text-lg font-black text-[var(--solar-primary-dark)]">{service.price}</div>{service.duration&&<div className="mt-1 text-xs text-slate-500">{service.duration}</div>}</div><span className="font-black text-[var(--solar-primary-dark)]">Chi tiết →</span></div></div></article></Link>;
}
